name: Linux
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
    tags:
      - '**'
  pull_request:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  test:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian-12-core
          - debian-12-gtk3
          - debian-12-qt5
          - debian-12-qt6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies to generate configure
        run: |
          sudo apt update
          sudo apt install -y -V \
            autoconf \
            autopoint \
            intltool \
            libtool \
            pkg-config
      - name: Generate configure
        run: |
          ./autogen.sh
          pushd sigscheme
          ./autogen.sh
          pushd libgcroots
          ./autogen.sh
          popd
          popd
      - name: Build Docker image
        run: |
          docker compose build ${{ matrix.image }}
      - name: Run Docker image
        run: |
          docker compose run ${{ matrix.image }}
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build Docker image
        run: |
          docker compose build debian-12-release
      - name: Run Docker image
        run: |
          docker compose run debian-12-release
      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: |
            *.sum
            *.tar.gz
            *.tar.bz2
      - name: Prepare release note
        run: |
          ruby \
            -e 'print("## uim ");
                puts(ARGF.read.split(/^## /)[1].
                       gsub(/\[(GH-\d+)\]\(.+?\)/) {$1}.
                       strip)' \
            NEWS.md | tee release-note.md

          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            previous_tag=$(git describe HEAD~ | cut -d- -f1)
          else
            previous_tag=$(git describe | cut -d- -f1)
          fi

          echo | tee -a release-note.md
          echo "### Contributors" | tee -a release-note.md
          echo | tee -a release-note.md
          command_line="git shortlog -sn ${previous_tag}.."
          echo "```console" | tee -a release-note.md
          echo "\$ ${command_line}" | tee -a release-note.md
          ${command_line} | tee -a release-note.md
          echo "```" | tee -a release-note.md
      - name: Publish
        if: |
          github.ref_type == 'tag'
        run: |
          title="$(head -n1 release-note.md | sed -e 's/^## //')"
          tail -n +2 release-note.md > release-note-without-version.md
          gh release create ${GITHUB_REF_NAME} \
            --discussion-category Announcements \
            --notes-file release-note-without-version.md \
            --title "${title}" \
            --verify-tag \
            uim-${GITHUB_REF_NAME}*
        env:
          GH_TOKEN: ${{ github.token }}
